**The following notebook contains the code I used to answer a series of questions about the winequality_red data.**

In [2]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from intro_Data_4_1 import *
from sklearn.preprocessing import StandardScaler as SS
from sklearn.linear_model import LogisticRegression as LR
from sklearn.ensemble import RandomForestClassifier as RFC

from intro_Data_4_3 import *
from sklearn.datasets import load_iris as li


work = pd.read_csv('./data/winequality_red.csv', sep=';')

In [3]:
newX = work.drop(columns = ['quality'])
y = work['quality'].values
X = np.array(newX)

In [4]:
#question 5

In [5]:
from sklearn.model_selection import train_test_split as tts
Xtrain,Xtest,ytrain,ytest = tts(X, y, test_size=0.4, random_state=146)

In [45]:
from sklearn.tree import DecisionTreeClassifier as DTC

dtc = DTC(random_state = 146) # 4 is optimal for decision tree
dtc.fit(Xtrain, ytrain)
print("Train accuracy is: ", dtc.score(Xtrain,ytrain))
y_pred = dtc.predict(Xtest)
conf_matrix, accuracy = compare_classes(ytest, y_pred)
conf_matrix
accuracy = dtc.score(Xtest, ytest)
accuracy

Train accuracy is:  1.0
Test accuracy = 0.63


0.6265625

In [46]:
from sklearn.metrics import confusion_matrix as CM
conf_matrix2 = CM(ytest, y_pred)
conf_matrix2

array([[  1,   0,   1,   0,   0,   0],
       [  0,   3,  12,  11,   1,   0],
       [  1,   5, 183,  63,   3,   0],
       [  0,   2,  62, 163,  27,   0],
       [  0,   1,   9,  35,  50,   0],
       [  0,   1,   0,   4,   1,   1]])

In [47]:
accuracy = dtc.score(Xtest, ytest)
accuracy

0.6265625

In [50]:
#100
rfc = RFC(random_state = 146, n_estimators = 100) # 5 is optimal for random forrest
rfc.fit(Xtrain, ytrain)
print("Train accuracy is: ", rfc_100.score(Xtrain,ytrain))
y_pred = rfc.predict(Xtest)
conf_matrix, accuracy = compare_classes(ytest, y_pred)
conf_matrix
accuracy = rfc.score(Xtest, ytest)
accuracy

Train accuracy is:  0.7247132429614181
Test accuracy = 0.65


0.6453125

In [51]:
from sklearn.metrics import confusion_matrix as CM
conf_matrix2 = CM(ytest, y_pred)
conf_matrix2

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,  22,   5,   0,   0],
       [  0,   0, 203,  50,   2,   0],
       [  0,   0,  65, 173,  16,   0],
       [  0,   0,   7,  51,  37,   0],
       [  0,   0,   0,   3,   4,   0]])

In [14]:
#500
rfc = RFC(random_state = 146, n_estimators = 500, max_depth = 5) # 5 is optimal for random forrest
rfc.fit(Xtrain, ytrain)
print("Train accuracy is: ", rfc.score(Xtrain,ytrain))
y_pred = rfc.predict(Xtest)
conf_matrix, accuracy = compare_classes(ytest, y_pred)
conf_matrix
accuracy = rfc.score(Xtest, ytest)
accuracy

Train accuracy is:  0.7122002085505735
Test accuracy = 0.59


0.590625

In [15]:
#1000
rfc = RFC(random_state = 146, n_estimators = 1000, max_depth = 5) # 5 is optimal for random forrest
rfc.fit(Xtrain, ytrain)
print("Train accuracy is: ", rfc.score(Xtrain,ytrain))
y_pred = rfc.predict(Xtest)
conf_matrix, accuracy = compare_classes(ytest, y_pred)
conf_matrix
accuracy = rfc.score(Xtest, ytest)
accuracy

Train accuracy is:  0.7174139728884255
Test accuracy = 0.59


0.5921875

In [16]:
#5000
rfc = RFC(random_state = 146, n_estimators = 5000, max_depth = 5) # 5 is optimal for random forrest
rfc.fit(Xtrain, ytrain)
print("Train accuracy is: ", rfc.score(Xtrain,ytrain))
y_pred = rfc.predict(Xtest)
conf_matrix, accuracy = compare_classes(ytest, y_pred)
conf_matrix
accuracy = rfc.score(Xtest, ytest)
accuracy

Train accuracy is:  0.7194994786235662
Test accuracy = 0.59


0.5921875

In [12]:
#question 6

In [13]:
#compared confusion matrix for DTC and RF

In [14]:
#question 7 

In [28]:
from sklearn.model_selection import train_test_split as tts
Xtrain,Xtest,ytrain,ytest = tts(X, y, test_size=0.4, random_state=146)

In [52]:
min_samples = np.arange(2,10) #2-9, will not include 10 


train = []
test = []
accuracy_list = []
#accuracy_list = []
for m in min_samples:
    rfc = RFC(n_estimators = 100,min_samples_split = m, random_state=146)
    rfc.fit(Xtrain, ytrain)
    #print("Train accuracy is: ", rfc.score(Xtrain,ytrain))
    y_pred = rfc.predict(Xtest)
    
    accuracy = rfc.score(Xtest, ytest) #question 8
    accuracy_list.append(accuracy)

print(accuracy_list)
    


[0.6453125, 0.6546875, 0.6390625, 0.6515625, 0.646875, 0.6484375, 0.6390625, 0.6359375]


In [ ]:
#question 8 

In [61]:
rfc = RFC(random_state = 146, n_estimators = 100, min_samples_split = 9) # 5 is optimal for random forrest
rfc.fit(Xtrain, ytrain)
print("Train accuracy is: ", rfc.score(Xtrain,ytrain))
conf_matrix, accuracy = compare_classes(ytest, rfc.predict(Xtest))
conf_matrix

Train accuracy is:  0.9228362877997914
Test accuracy = 0.64


Predicted    5    6   7
Actual                 
3            2    0   0
4           22    5   0
5          207   47   1
6           73  169  12
7            7   57  31
8            0    3   4

In [ ]:
# question 9

In [37]:
from sklearn.model_selection import KFold, GridSearchCV

# create a grid of parameter values
param_grid_rfc = dict(n_estimators=[100],max_depth = [2,3,4,5,6,7,8,9,10],min_samples_split= [2, 3, 4, 5]) #IF YOU DONT MAKE IT WONT WORK; must be a DICTIONARY
# specify how you want to do the cross-validation
cv = KFold(n_splits=5, random_state=146, shuffle = True)
grid_rfc = GridSearchCV(RFC(random_state = 146), param_grid=param_grid_rfc, cv=cv, 
                    scoring='accuracy')

# perform grid search (what is this really doing?)
grid_rfc.fit(X, y)

GridSearchCV(cv=KFold(n_splits=5, random_state=146, shuffle=True),
             estimator=RandomForestClassifier(random_state=146),
             param_grid={'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'min_samples_split': [2, 3, 4, 5],
                         'n_estimators': [100]},
             scoring='accuracy')

In [38]:
print(
    f'The best parameters are {grid_rfc.best_params_} with a score of {grid_rfc.best_score_:.2f}'
)

The best parameters are {'max_depth': 10, 'min_samples_split': 4, 'n_estimators': 100} with a score of 0.69


In [ ]:
#question 10

In [75]:
#optimized paramaters : score = 0.63
rfc = RFC(random_state = 146, n_estimators = 100, max_depth = 10, min_samples_split = 4) # 5 is optimal for random forrest
rfc.fit(Xtrain, ytrain)

y_pred = rfc.predict(Xtest)

accuracy = compare_classes(ytest, y_pred)

accuracy = rfc.score(Xtest, ytest)
accuracy

Test accuracy = 0.63


0.6296875

In [76]:
#default parameters: score= 0.6
rfc = RFC(random_state = 146, n_estimators = 100, max_depth = 5) # 5 is optimal for random forrest #should I have included min_samples_split>
rfc.fit(Xtrain, ytrain)

y_pred = rfc.predict(Xtest)

accuracy = compare_classes(ytest, y_pred)

accuracy = rfc.score(Xtest, ytest)
accuracy

Test accuracy = 0.60


0.5953125

In [74]:
#mean test accuracy (from above) Average for validation: 0.62

#0.6161330581761006

#2-9, will not include 10 


train = []
test = []

accuracy_list = []
for m in min_samples_split:
    rfc = RFC(n_estimators = 100, max_depth = 10, min_samples_split = 4, random_state=146)
    tr,te  = do_Kfold(rfc,X,y,k)
    train.append(np.mean(tr))
    test.append(np.mean(te))
    #print(tr[5]) 
    
    accuracy = rfc.score(Xtest, ytest) #question 8
    accuracy_list.append(accuracy)
    #print(accuracy)

NameError: name 'k' is not defined

In [ ]:
print('Average for validation:', format(np.mean(accuracy)))

In [ ]:
# question 11/12 

In [77]:
rfc = RFC(random_state = 146, n_estimators = 100, max_depth = 10, min_samples_split = 4) # 5 is optimal for random forrest
rfc.fit(Xtrain, ytrain)

y_pred = rfc.predict(Xtest)

accuracy = compare_classes(ytest, y_pred)

accuracy = rfc.score(Xtest, ytest)
accuracy

Test accuracy = 0.63


0.6296875

In [ ]:
rfc.predict(Xtest[0].reshape(-1,1))

In [ ]:
#question 11

In [78]:
X_mean = np.mean(X, axis =0)

In [80]:
X_mean

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311])

In [82]:
rfc.predict_proba(X_mean.reshape(1,-1))

array([[0.00060257, 0.00884662, 0.38687751, 0.55032794, 0.0514418 ,
        0.00190356]])